// autogenerated by circom
const wc  = require("./witness_calculator.js");
const { readFileSync, writeFile } = require("fs");

const input = JSON.parse(readFileSync(process.argv[3], "utf8"));

const buffer = readFileSync(process.argv[2]);
wc(buffer).then(async witnessCalculator => {
const buff= await witnessCalculator.calculateWTNSBin(input,0);
writeFile(process.argv[4], buff, function(err) {
	if (err) throw err;
});
});